[workspace]
resolver = "3"
members = ["crates/*", "examples/*", "support/guest-build"]

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"
repository = "https://github.com/luizribeiro/wasm-component-middleware"
version = "0.0.0"

[workspace.dependencies]
anyhow = "1"
http = "1"
hyper = "1"
rustls = { version = "0.23", default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
wasmtime = { version = "49", default-features = false, features = [
  "component-model",
  "component-model-async",
  "runtime",
] }
wasmtime-wasi = "49"
wasmtime-wasi-http = "49"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = "warn"
