package test:http-coverage;

world imports {
  import wasi:http/types@0.2.12;
  import wasi:http/outgoing-handler@0.2.12;
}

world proxy-imports {
  include imports;
  import wasi:cli/stdin@0.2.12;
  import wasi:cli/stdout@0.2.12;
  import wasi:cli/stderr@0.2.12;
  import wasi:clocks/monotonic-clock@0.2.12;
  import wasi:clocks/wall-clock@0.2.12;
  import wasi:io/error@0.2.12;
  import wasi:io/poll@0.2.12;
  import wasi:io/streams@0.2.12;
  import wasi:random/random@0.2.12;
}

world command-imports {
  include imports;
  include wasi:cli/imports@0.2.12;
}
