[package]
name = "wasm-component-middleware"
description = "Middleware for WebAssembly component calls"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
wasmtime.workspace = true

[dev-dependencies]
guest-build = { path = "../../support/guest-build" }
wasmtime = { workspace = true, features = ["cranelift"] }
wasmtime-wasi.workspace = true

[lints]
workspace = true
