[package]
name = "wasm-component-middleware-wasi"
description = "WASI middleware for WebAssembly component calls"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
wasm-component-middleware = { path = "../wasm-component-middleware", version = "0.0.0" }
wasmtime.workspace = true
wasmtime-wasi.workspace = true

[dev-dependencies]
bytes = "1"
test-guests = { path = "../test-guests" }
tokio.workspace = true
wasmtime = { workspace = true, features = ["cranelift"] }
wit-component = { version = "0.258", features = ["dummy-module"] }
wit-parser = "0.258"

[lints]
workspace = true
