[package]
name = "deny"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
guest-build = { path = "../../support/guest-build" }
wasm-component-middleware = { path = "../../crates/wasm-component-middleware" }
wasmtime = { workspace = true, features = ["cranelift"] }
wasmtime-wasi.workspace = true

[lints]
workspace = true
