[package]
name = "test-guests"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]

[dev-dependencies]
tokio.workspace = true
wasmtime = { workspace = true, features = ["cranelift"] }
wasmtime-wasi.workspace = true

[lints]
workspace = true
